// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Data;

#nullable disable

namespace WarehouseManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250610121558_descriptionnull")]
    partial class descriptionnull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WarehouseManagement.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "15\" notebook",
                            LocationId = 1,
                            Name = "Notebook Dell XPS",
                            Quantity = 5m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bezdrátová myš",
                            LocationId = 2,
                            Name = "Myš Microsoft",
                            Quantity = 10m
                        },
                        new
                        {
                            Id = 3,
                            Description = "27\" monitor",
                            LocationId = 3,
                            Name = "Monitor LG",
                            Quantity = 3m
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShelfId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A1-01",
                            Description = "Lokace A1-01",
                            ShelfId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "A1-02",
                            Description = "Lokace A1-02",
                            ShelfId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "B1-01",
                            Description = "Lokace B1-01",
                            ShelfId = 2
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Shelves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A1",
                            Description = "Regál A1",
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "B1",
                            Description = "Regál B1",
                            WarehouseId = 1
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Centrální skladový prostor",
                            Name = "Hlavní sklad"
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Item", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Location", "Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Location", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Shelf", "Shelf")
                        .WithMany("Locations")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Shelf", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("Shelves")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Location", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Shelf", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Warehouse", b =>
                {
                    b.Navigation("Shelves");
                });
#pragma warning restore 612, 618
        }
    }
}
